### ISSUE TITLE
Could add a README for the project

### ISSUE THREAD

**Issue by owenvoke** [mosesfinlay/vdnote#1]
I was just reading your blog post. Saw this, and I was thinking it may be nice to add a README explaining about the project, how to use it, and maybe how it works. :relaxed:

I might make a pull request for one. :+1:

**Comment by branditodesigns** [comment]
+1

**Comment by owenvoke** [comment]
A basic [`README`][readme] has been added in ffffa53ab2849b2ecf176fe41a8ba90aa5229579

[readme]: https://github.com/mosesfinlay/vdnote/blob/ffffa53ab2849b2ecf176fe41a8ba90aa5229579/README.md
